#!/bin/bash
set -e

echo "Starting OurBr00d pipeline..."

# Reset lessons.md to HEAD before pulling — it was generated by the server
# and already rsync'd to Mac. The pull then fetches the Mac-pushed version.
git pull || echo "Warning: git pull failed — continuing with local state."

# Stop our own containers cleanly if still running (e.g. after unexpected crash)
docker compose down 2>/dev/null || true

# Port check: ports 8011 + 8002 must be free. If occupied, another container
# (different compose project or another group) holds the port — we don't touch it.
for port in 8011 8002; do
    if ss -tlnp | grep -q ":${port} "; then
        echo "ERROR: Port ${port} is already in use."
        echo "   Check running containers: docker ps"
        echo "   Stop the blocking container, then try again."
        exit 1
    fi
done

docker compose up -d --build

# Build the static knowledge base once. The index (knowledge_db/) is gitignored
# and does NOT come with a fresh clone — only the corpus (m0ther_RAG/) is in git.
# Without this step Mother runs silently without background knowledge (server.py
# handles it gracefully, no crash, but KB stays off). Only build when not present
# — otherwise every start wastes GPU/time. Runs INSIDE the container (CUDA + chromadb).
# A build failure must not abort start.sh (|| echo) — pipeline runs without KB if needed.
if [ ! -d knowledge_db ] || [ -z "$(ls -A knowledge_db 2>/dev/null)" ]; then
    echo "Knowledge base not found — building index once (inside container)..."
    docker compose exec -i whisper python3 /app/build_knowledge_base.py \
        || echo "WARNING: KB build failed — pipeline continues without static knowledge."
fi

echo "Pipeline ready — starting server (kill phrase to end)..."
echo ""

# Ctrl+C must not kill this shell
trap '' INT

# setsid --wait: docker exec runs in its own session (no terminal signal can reach it),
# --wait keeps this process alive until server.py exits → then exec bash for an interactive prompt.
setsid --wait docker compose exec -i -e PYTHONUNBUFFERED=1 whisper python3 -u /app/server.py

echo ""
echo "── Server stopped — interactive shell ──"
exec bash
